from .statement import *
from .for_statement import *
from .call_statement import *
from .set_statement import *
from .if_statement import *
from .call_statement import *
from .print_statement import *
from .return_statement import *
from .call_statement import *
from .set_statement import *